# .swiftlint.yml
#whitelist_rules: # Liste seulement les règles que vous voulez activer
#  - empty_count
#  - trailing_whitespace

trailing_whitespace:
  ignores_empty_lines: false # Mettez à 'true' pour ignorer les lignes vides
  ignores_comments: true # Mettez à 'true' pour ignorer l'espace de fin dans les commentaires

vertical_whitespace:
  max_empty_lines: 1


line_length:
  warning: 200
  error: 250

# Vous pouvez également désactiver certaines règles si elles ne sont pas pertinentes pour votre projet
disabled_rules: # règles à désactiver
  - todo
  - file_length
  - nesting
# Exclure les fichiers et les dossiers du linting
excluded: # chemins à exclure du linting
  - Carthage
  - Pods
  - SomeSpecificFile.swift

